---
- name: Deploy MyNetwork Services to Kubernetes Cluster
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Apache Deployment
      kubernetes.core:
        definition: "{{ lookup('file', 'apache-deployment.yaml') }}"
    
    - name: Apply Apache Service
      kubernetes.core:
        definition: "{{ lookup('file', 'apache-service.yaml') }}"
    
    - name: Apply BIND Deployment
      kubernetes.core:
        definition: "{{ lookup('file', 'bind-deployment.yaml') }}"
    
    - name: Apply BIND Service
      kubernetes.core:
        definition: "{{ lookup('file', 'bind-service.yaml') }}"
    
    - name: Apply DHCP Deployment
      kubernetes.core:
        definition: "{{ lookup('file', 'dhcp-deployment.yaml') }}"
    
    - name: Apply DHCP Service
      kubernetes.core:
        definition: "{{ lookup('file', 'dhcp-service.yaml') }}"

  handlers:
    - name: restart apache
      kubernetes.core:
        definition: "{{ lookup('file', 'apache-restart.yaml') }}"
    
    - name: restart bind
      kubernetes.core:
        definition: "{{ lookup('file', 'bind-restart.yaml') }}"
    
    - name: restart dhcp
      kubernetes.core:
        definition: "{{ lookup('file', 'dhcp-restart.yaml') }}"
