---
- name: Deploy Services on Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Apply DHCP Deployment
      k8s:
        state: present
        definition: "{{ lookup('template', 'dhcp-deployment.yaml') }}"
      register: dhcp_result

    - name: Apply Apache Deployment
      k8s:
        state: present
        definition: "{{ lookup('template', 'apache-deployment.yaml') }}"
      register: apache_result

    - name: Apply DNS Deployment
      k8s:
        state: present
        definition: "{{ lookup('template', 'dns-deployment.yaml') }}"
      register: dns_result

    - name: Wait for services to be ready
      k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: default
        label_selectors:
          - app in (mynetwork-dhcp, mynetwork-apache, mynetwork-dns)
      register: deployment_info
      until: deployment_info.resources | selectattr('status.readyReplicas', 'defined') | map(attribute='status.readyReplicas') | list == [1, 1, 1]
      retries: 10
      delay: 10

    - name: Print deployment results
      debug:
        msg: "{{ item.0.name }} deployment status: {{ item.1 | json_query('resources[0].status') }}"
      loop:
        - { name: "DHCP", status: "{{ dhcp_result }}" }
        - { name: "Apache", status: "{{ apache_result }}" }
        - { name: "DNS", status: "{{ dns_result }}" }
